---
#This playbook deploys the whole application stack in this site.
- hosts: all
  remote_user: ansible
  roles:
   - common

#This playbook deploys the whole weberver stack in this site.
- hosts: webservers
  remote_user: ansible
  roles:
    - web

# This playbook deploys the whole db stack in this site.
- hosts: dbservers
  remote_user: ansible
  roles:
    - db
