---
 # - name: Install httpd and php
 #   yum: 
 #     name: php 
 #  state: present
 #   with_items:
 #    - httpd
 #    - php
 #    - php-mysql
 #    - python
 #   when: ansible_facts['distribution'] == "RedHat"

  - name: Install httpd and php
    apt: 
      name: apache2 
      state: present
    with_items:
     - apache2
     - php
     - php-mysql
    when: 
     ansible_facts['distribution'] == "Ubuntu"

  - name: Install web role specific dependencies
    apt: 
      name: git
      state: present
    with_items:
    - git
    when: 
     ansible_facts['distribution'] == "Ubuntu"
    
  - name: http service state
    service: 
      name: apache2
      state: started
      enabled: yes
    when: 
     ansible_facts['distribution'] == "Ubuntu"
      
#  - name: Configure SELinux to allow httpd to connect to remote database
#    seboolean: 
#      name: httpd_can_network_connect_db 
#      state: yes 
#      persistent: yes
#    when: 
#     ansible_facts['distribution'] == "Ubuntu"
