# This playbook contains common plays that will be run on all nodes.
  - name: Install Chrony
    yum: name=chrony state=present
    tags: ntp/chrony
    when: ansible_facts['distribution'] == "CentOS"
  
  - name: Install ntp
    become: yes
    apt: name=ntp state=present
    tags: ntp/ntp
    when: ansible_facts['distribution'] == "Ubuntu"

  - name: Install common dependencies
    apt:
      name: 
        - firewalld
      state: present
    when: ansible_facts['distribution'] == "Ubuntu"

  - name: Configure ntp file
    become: yes
    template: 
      src: /home/ansible/ansible/obligatorio_2021_08/lamp/roles/common/templates/ntp.conf.j2
      dest: /etc/ntp.conf
    tags: ntp
    notify: restart ntp
    when: ansible_facts['distribution'] == "Ubuntu"
